README.md

My blog takes precedence over SegmentFault

Change tutorials url

---

README.md

Is this an ok place to put this? Or should I put it under 'Starter Template' with the other official supported templates?

Added Vueniverse

---

README.md

creates a new section for docker and add reference to nuxt docker image

add nuxt docker image reference

---

README.md

Addition of CSS-Tricks resource, breaking down page transitions from CSS animation to JS Hooks, with transition modes.

Add in CSS-Tricks article

---

README.md

I've created this module to interact with an OAuth 2 server for Nuxt (which we're soon going to be using in production), thought people might find it useful 👍

Add nuxt-oauth

---

README.md

New complete tutorial of Nuxt.js in spanish language

New tutorial in spanish language

---

README.md

Hey, I built yesterday and today this WP API wrapper.
https://github.com/yashha/wp-nuxt
Best Regards

Added wordpress module

---

README.md

Nuxt integration with https://github.com/vuematerial/vue-material

Add nuxt-vue-material to community modules

---

README.md

Nuxt module for https://github.com/thesabbir/simple-line-icons

Add Simple Line Icons module

---

README.md

Move BR Podcast from Project to Showcase

---

README.md

Just adding another project we're developed locally in Mauritius using Nuxt.js in the list.

Added Rewind 2017 in the Projects Using Nuxt.js section

---

README.md

https://medium.com/@k33g_org/create-and-deploy-a-nuxt-js-application-on-clever-cloud-in-a-few-moments-47474059d849
Clever Cloud (https://www.clever-cloud.com/) is a PaaS platform

Add New Tutorial About Deploy a Nuxt App on Clever-Cloud

---

README.md

Hello, a few days ago I tried to make an application with nuxtjs.
i love nuxt. So, I want the world to know, nuxtjs is very awesome

add new site use nuxtjs

---

README.md

https://github.com/cretueusebiu/laravel-nuxt

Add a Laravel-Nuxt starter project template

---

README.md

fix thalitajacinda.com

---

README.md

VueBlog is a lightweight blog application for note-taking

Add  VueBlog

---

README.md

https://github.com/skyrpex/laravel-nuxt-js
This package makes super easy to create a SPA along with Laravel as an API.

Add laravel-nuxt

---

README.md

You can use `cookie-universal-nuxt` to set, get and remove cookies in both client and server side nuxt apps. `cookie-universal-nuxt` parse cookies with the popular cookie node module.

Add cookie-universal-nuxt

---

README.md

Supports ES6 imports with tree shaking. Also is better documented.

Alternative module for Fontawesome 5 integration

---

README.md

Added K-Beauty landing page to showcase

---

README.md

What else can I say except that I added the link to this module? :wink:

Add nuxt-rfg-icon plugin

---

README.md

The title says it all I guess :+1:

Add nuxt-matomo plugin

---

README.md

Just added the Nuxt-Validate module; a simple Nuxt input validation module using vee-validate. https://github.com/lewyuburi/nuxt-validate

Adding Nuxt-Validate module

---

README.md

https://www.homeday.de/preisatlas/de-DE

[Task] Add preisatlas to showcase

---

README.md

Add frontend boilerplates starter template

Add starter template

---

README.md

Adding our company website!! 🔥

Add Colle McVoy website to projects using Nuxt

---

README.md

We'd be delighted for you to showcase these three sites we had the privilege of building with our partners: https://github.com/joshuabryant/awesome-nuxt/tree/patch-1#showcase
—Josh, [Journey Group](http://www.journeygroup.com)

Adds three websites to Showcase

---

README.md

Add PWA builder

---

README.md

add sum.cumo to the list of projects using nuxt.js
Thank you nuxt.js team for such an awesome project 🙏

sum.cumo uses nuxt.js

---

README.md

academind.com was re-written from scratch and now uses Nuxt.js.
https://github.com/maxschwarzmueller/awesome-nuxt/tree/patch-1

Added academind.com, a website built with Nuxt.js

---

README.md

Nuxt7 integrates universal nuxt.js applications with Framework7-Vue to rapidly create efficient and feature-reach PWA mobile applications with help of pwa-module. Production builds can be statically hosted or running offline.

Nuxt7/Framework7-Vue added to community cat.

---

README.md

add my personal site to the list, it is a combination out of a blog and portfolio. Built with Nuxt.js and custom styling (just using pure css as grid). Great project btw :+1:

Add my personal site to list

---

README.md

add a nuxt project

---

README.md

Added Charly Zenger Project To "Projects Using Nuxt.js" Section

Added Charly Zenger Project To "Projects Using Nuxt.js" Section

---

README.md

Add nuxt-generate-cluster in new section "Tools"

---

README.md

Just created nuxt-express-module that allows you to have an express server using the serverMiddleware. The module also comes with hot reload so updates in the code reloads without a server restart.

Added Nuxt Express to the community modules

---

README.md

This project use many thing about nuxtjs and vuejs community
such as i18n, vuex, express, iviewui, etc.
It's still in alpha version.

Add exemple of project using NuxtJs - DBAdventure

---

README.md

A setup to build beautiful documentation with Nuxt and Storyblok deployed on Netlify for everyone.
- https://github.com/storyblok/nuxtdoc

Adds NuxtDoc

---

README.md

Add this tiny module to the community list.

Add nuxt typescript module.

---

README.md

https://github.com/wemake-services/nuxt-imagemin
I have also updated description of `nuxt-babel`. Since it is changed.

Adds nuxt-imagemin

---

README.md

Book Store Page: https://booth.pm/ja/items/824745
Support Repository: https://github.com/potato4d/nuxt-tech-book
It is a doujinshi introducing Nuxt.  
Analog book & e-Book total 300 sales over! :tada:

Add Nuxt tech book

---

README.md

Adds a site to the showcase list: [www.teakandtwine.com](https://www.teakandtwine.com).

Adds Showcase Site: www.teakandtwine.com

---

README.md

Create your middleware api using a universal access point approach from your vue pages.

[nuxt-neo] - create and access api module

---

README.md

Adds Parkmaven to showcase

---

README.md

Hey,
I added my personal portfolio to the list of projects using nuxt (alainperrier.me). My code certainly needs to be cleaned, but I think some integrations I made (Laravel, Tailwind, PurgeCSS, PWA...) could be helpful to the community.
Hope you will share :)

Add my personal portfolio to "projects using nuxt"

---

README.md

Link to website: https://vuepeople.org link to repo: https://github.com/pulilab/vue-people

add vuepeople.org to showcase section

---

README.md

Hey,
I added nuxt-mq, a tiny Nuxt module that wraps vue-mq, to the community modules.
Thank you!

Add nuxt-mq

---

README.md

Please pull into the main branch. Added new entry into the showcase. Thx.

Added Y-Verge.com into showcase section

---

README.md

https://github.com/galvez/nuxpress

Add galvez/nuxpress, a markdown blogging engine and boilerplate written in Nuxt.js

---

README.md

Add a Thinkjs-Nuxt starter project template

https://github.com/thinkjs/thinkjs

---

README.md

Adding a project I recently finished to the "Projects Using Nuxt.js" section.

add mono-1.com to Projects using Nuxt.

---

README.md

This is a tool I wrote for automating my deployment of my Nuxt.js projects.  I have 4 in production now all using it.

addition of aeonian

---

README.md

edited previous description on charly zenger project

Added Axure Broker new website

---

README.md

This module adds clientInit to Nuxt.js.
I hope it merges if you like!

Added nuxt-client-init-module

---

README.md

Adding a new website built with Nuxt

New project Link - thegaelicpoint

---

README.md

Hey!
I'd propose a new section called "blogs" where people could add their own (or other) interesting blogs where they also write articles about Nuxt.js.

Add a "blogs" section

---

README.md

Adds a site to the showcase list: https://be.camp

Adds Showcase Site: https://be.camp

---

README.md

+ Fix link for error page blog post

Add Brotli blog post

---

README.md

Hi,
A simple pr to add my package to community modules

Add Nuxt Rollbar Module to Community modules

---

README.md

I made a bt search engine by nuxtjs and nuxt-i18n, I hope this website can be added to showcase. Thank you guys!

Add torrent search engine [BTZhai] to the showcase

---

README.md

- [nuxt-elm](https://github.com/EasyTuan/nuxt-elm/) - Full-stack open source project based on vue2 + nuxt.[Performance demonstration](https://elm.caibowen.net/).

 I added a nuxt project recommendation

---

README.md

Please add the Nuxt Image Loader Module under the Modules > Community heading.

Add Nuxt Image Loader Module

---

README.md

Add [nuxt-storage](https://github.com/mazipan/nuxt-storage) to the list

Add nuxt-storage to the list

---

README.md

Add my last project developed with nuxt. It would be great be part of this awesome list!

Add new project made with Nuxt

---

README.md

- [bitkris-dev/bolide-nuxt-template](https://github.com/bitkris-dev/bolide-nuxt-template) - Question-based template (CSS framework choice + preinstalled modules).

Adding a new template / boilerplate

---

README.md

Shamelessly plugging the article I wrote praising nuxt's approach

Added tutorial on building restful UI's with Nuxt

---

README.md

I have added thesettlement.co.nz which I have recently completed to the showcase section.

added thesettlement.co.nz to the showcase section

---

README.md

I published a book: tada:
https://www.amazon.co.jp/dp/4863542569/
There are both real books and e-Book (Kindle).
However, it is written in Japanese.

Add "Nuxt.js beginners guide"

---

README.md

Add SSR component guide

---

README.md

Add "build.templates" blog article

---

README.md

rel: https://github.com/sindresorhus/awesome/pull/1100#issuecomment-408628551

Resize image to half of it's original width

---

README.md

Added Rivalry to Projects using Nuxt.js

---

README.md

related: https://github.com/sindresorhus/awesome/pull/1100#issuecomment-408628551, https://github.com/sindresorhus/awesome/pull/1420#issuecomment-433685022

Fix issues from awesome-lint

---

README.md

https://github.com/brunosalgado/awesome-nuxt

Add Rentcars.com to the Showcase Section

---

README.md

The prismic-nuxt repository can be found here: https://github.com/jamespegg/prismic-nuxt

Adding prismic-nuxt to the list

---

README.md

added [flagpack](https://flag.pk). The website uses vueJS & nuxtJS

Added flag.pk to the showcase

---

README.md

Add nuxt-netlify-http2-server-push

---

README.md

Nuxt integration with https://alvarotrigo.com/fullPage/

Add nuxt-fullpage.js to community modules

---

README.md

Nuxt integration with https://river-lee.github.io/vue-fullpage/

Add fullpage-nuxt to community modules

---

README.md

- [TecnoSpeed](https://tecnospeed.com.br) - An brazilian business focused in make solutions to others developers.
- [PlugNotas](https://plugnotas.com.br) - An service to emit service invoices in Brazil

feat: add plugnotas.com.br and tecnospeed.com.br

---

README.md

Adding our website http://readable.report/ to the showcase section of the README.md. We built our entire app with Nuxt and think it's worthy to be showcased.

Adding readable.report to showcase section.

---

README.md

Please let me add this module!
Repo: https://github.com/potato4d/nuxt-basic-auth-module
Star: 77 GitHub stars(2019/01/06)

Add nuxt-basic-auth-module to community module

---

README.md

- I added a few community modules that I knew were missing from the list.
- I also added `alibaba.aero` as a website powered by Nuxt.js.

feat: add missing community modules and alibaba

---

README.md

A couple of projects I'm actively working on that use NuxtJS 😄

Add Tyneside Lettings and R6Stats

---

README.md

Organization chart edit/view build wit Vue2 and made a static website with Nuxt

added vue-org-chart

---

README.md

Adding Showcase: Scale Leap

---

README.md

Cloud CMS nuxt integration
https://github.com/gitana/cloudcms-nuxt

add cloudcms-nuxt

---

README.md

This project is made with Nuxt and Vuetify

Add new showcase

---

README.md

I think a duplicated link might have been added by mistake. Thanks for curating the list btw!

Remove duplicated link

---

README.md

Github -> [https://github.com/spektrummedia/nuxt-vue-multiselect](https://github.com/spektrummedia/nuxt-vue-multiselect)
npm -> [https://www.npmjs.com/package/nuxt-vue-multiselect](https://www.npmjs.com/package/nuxt-vue-multiselect)
Cheers!

Add nuxt-vue-multiselect to community modules

---

README.md

Dynamically generate `_headers` and `_redirects` files for Netlify in your Nuxt.js projects.

add Nuxt Netlify

---

README.md

A new module for nuxt: Nuxt Optimized Images, Automatically optimizes images used in Nuxt.js projects (JPEG, PNG, SVG, WebP and GIF).

add nuxt-optimized-images

---

README.md

Added Zip Stores as one of the showcases using nuxt.js

Added Zip Stores as one of the showcases

---

README.md

I built my website using Nuxt JS.

Added Ide.ma to `Projects Using Nuxt.js`

---

README.md

A working example of ecommerce for food ordering.

Adding foodfire(open source) to `Projects Using Nuxt`

---

README.md

I build my master thesis website using Nuxt.js

Add i-consent.network to `Projects Using Nuxt`

---

README.md

add russian telegram community

add russian telegram community

---

README.md

Hi,
I created a nuxt module to easily add Zendesk Web Widget to a nuxt app !
Regards

Add nuxt-zendesk community module

---

README.md

Wuxt is an integrated development environment, which starts development ready docker containers for headless WordPress and Nuxt with one command. 
Wuxt brings additions to the WP Rest API (menus, front-page, slug requests, meta fields), which make building nuxt-apps on top of it much more easy. Additionally the initial nuxt app provides a complete WP-API connector. Worth adding I hope!

Adding wuxt

---

README.md

First Angolan website made in Nuxt, up and running...
https://cinemax.co.ao
Big thanks for our **community**!

 Added Cinemas Cinemax official website.

---

README.md

Hello,
I have created a Nuxt module to manage feature toggles.
This update will add the module to the community module list.
Thank you.

Add nuxt-feature-toggle community module

---

README.md

add showcase SUSHI :sushi:

---

README.md

Add nuxt-markdown-blog-starter link to Starter Template section

---

README.md

A small module for adding parse support to nuxt.js

Added nuxt-parse as module

---

README.md

I added Social Design under Projects 🚀

Added Social Design

---

README.md

I made a guide explaining how to create a Nuxt application and convert it to Typescript, also I'm using Koa and Serverless to run the application =)

Adding Tutorial for Nuxt with Typescript, Koa and Serverless

---

README.md

Please add our first Magento 2 PWA 🙇

Added showcase Soane

---

README.md

Adding Article about how to reduce the size of the Nuxt files in 10%-20% with Brotli and how to set up this in Cloudfront.

Adding new Article

---

README.md

Added Vendic website to the showcase

Added Vendic website to the showcase

---

README.md

nuxt-mobile-detect is a wrapper around mobile-detect.js (https://github.com/hgoebl/mobile-detect.js) that allows you to access information about the user agent server side and client side.
https://github.com/ChanningDefoe/nuxt-mobile-detect

Add nuxt-mobile-detect Module

---

README.md

A new official package for detecting device type.

Add @nuxtjs/device-module

---

README.md

Nuxt starter template project. 
https://github.com/RadKod/RKnuxtstarterkit
Axios, style resources module, modular vuex store with samples. And more.

Add: RKnuxtstarterkit

---

README.md

https://github.com/tomimick/tm-nuxtjs-starter - A minimal starter/demo with axios/localstorage, SASS, static site export, live demo

New starter/demo tomimick/tm-nuxtjs-starter

---

README.md

* fixes #287 
* escape pipe characters that cause gh page render table rows/cells

escape pipe characters

---

README.md

Two sites are built by nuxt ssr. Glad to share the experience of using nuxt to build the frontend or even the backend of a website.

Update README.md add two sites built by nuxt

---

README.md

Added 2 sites built completely with Nuxt 2

Updated showcase to add 2 more example sites

---

README.md

This adds [nuxt-vue-select](https://github.com/madmod/nuxt-vue-select) as a community module.

Add nuxt-view-select

---

README.md

Hope people find this useful, official docs on how to use the Ghost API with Nuxt.js 👻 
Link added: https://ghost.org/docs/api/nuxtjs/

Add Working with Ghost and Nuxt.js

---

README.md

I updated the Nuxt.js logo in the README.md.

update Nuxt.js logo

---

README.md

I'm surprised that you guys don't list this module

Add official TailwindCSS module

---

README.md

- https://github.com/nuxt-community/amp-module

add official AMP module

---

README.md

I fixed some errors that i got after linting the README.md with [awesome-lint](https://github.com/sindresorhus/awesome-lint).
There are still some errors left.
---
**Please add [awesome-lint](https://github.com/sindresorhus/awesome-lint) as a test script in package.json and activate Travis CI to lint on new commits and pull requests.
See: https://github.com/sindresorhus/awesome-lint#tip
This prevents formatting errors, spelling mistakes etc. (like the ones in this pr). And it also makes it easier to maintain this list in general.**
⚠

fix awesome-lint errors

---

README.md

Postwoman (https://postwoman.io) is an web online, open sourced API request builder - Helps you create your requests faster, saving you precious time on your development https://github.com/liyasthomas/postwoman

Adds postwoman.io in "Projects Using Nuxt.js" section

---

README.md

Update README.md to add 36 Pixels

---

README.md

I fixed a formatting error. And i also fixed some errors that i accidentally added in #300 (oops 😅).
---

fix awesome-lint errors, part 2

---

README.md

https://github.com/yashha/wp-nuxt-stack-starter

Added wp-nuxt-stack-starter

---

README.md

Site showcases not only the performance of the Nuxt production server, but also showcases the use of server middleware for making API calls.

Add JessFlix to showcase

---

README.md

Just npm install the module and add 1 line to nuxt.config to enable storybooking. Stories are similar to pages: story routes are auto-created for stories placed in the ".stories" folder

Nuxt stories module

---

README.md

Added example from theoddwave.co.nz

Added example from theoddwave.co.nz

---

README.md

Disposable temporary email service built with Nuxt and Vue.js.

Added temp-mail.io to Showcase

---

README.md

For further info of Freshworks visit - [Freshworks](https://www.freshworks.com)

Added Freshworks Marketplace to showcase list

---

README.md

Changed the domain for the tool and updated the new URL to [OpenGraph](https://www.opengraph.xyz).

Update Social Design URL

---

README.md

Nuxt.js and moment.js have created an easily integrated module. Because moment.js is added as a nuxt plugin and added to context, it is easy to use them through `$moment`.

Added nuxt-moment-module to Modules

---

README.md

just made a new yeoman generator for a fully deployable nuxt stack that templatizes something that I've been using for a while now.

adding suf-stack/generator-suf-stack-aws-koa-nuxt

---

README.md

Just found three dead links to projects that don't exist anymore and added the docker section to the toc.

Remove dead project links

---

README.md

Hi!!
I just added our most recent project to the showcase section.
Publish it if you like it.
Thank you!!

Just added a new project to the showcase

---

README.md

Module to prune html before sending it to the browser (it removes elements matching CSS selector(s)).
These library was born to remove scripts injected in the HTML only if a visitor is a Bot or a Chrome Lighthouse.
This should speed up performance.

Added nuxt-purge-html to Modules

---

README.md

- make Nuxt app as sub application with qiankun or single-SPA
- demo https://deep-han.github.io/qiankun

chore: add modules about micro-frontend

---

README.md

Cache api resources and serve it as static resource with Nuxt.js [documentation](https://xhr-cache.dewib.com) @Atinux

Added xhr-cache to Modules

---

README.md

Though the title only includes Vue, it's highly relevant for Nuxt.js users

Add new blog post

---

README.md

feat: add module template with Ava

---

README.md

We switched to Mapbox around a year ago :)

Update Preisatlas description

---

README.md

[Holt Soundboard](https://nine-nine.now.sh/) is a soundboard of all characters from the show Brooklyn Nine-Nine.
It makes use of Vuex, and Nuxt's static generation feature for better SEO.
It is [open-source](https://github.com/holt-soundboard/holt-soundboard-web).

Added Holt Soundboard

---

README.md

add project 'CMD Generators'

---

README.md

Added a link to the nuxt-highcharts module I created, based off highcharts-vue with performance improvements.

Nuxt-highcharts module

---

README.md

All of your favorite testing utils in one place. Added a few to help speed up module and plugin testing.
(Also rebased on top of my previous PR, so if that one gets in, this one should be in sync)

Nuxt test utils

---

README.md

Hi!
This PR introduces Chakra UI Vue community packages including it's Nuxt Module.

feat: add Chakra UI Vue community packages

---

README.md

This is our simple nuxt project that allows people to add their pride flag of choice on their images or GIFs!
Let me know if there's anything else you'd like me to add/correct! 😄

Add pfp.lgbt to the list

---

README.md

Add Journalistic to Projects using Nuxt.js

---

README.md

- [d-patterns.js.org](https://d-patterns.js.org) - FOSS Discord templates listing website 💬

Add open source project : d-patterns.js.org

---

README.md

add website using nuxt

---

README.md

Added [@nuxtjs/color-mode](https://github.com/nuxt-community/color-mode-module) module

Added @nuxtjs/color-mode module

---

README.md

Package link: https://github.com/nuxt-community/cloudinary-module

add nuxt/cloudinary module

---

README.md

Just update yandex-metrika module url 😀

feat: update yandex-metrika module url

---

README.md

I've added modules.nuxtjs.org to readme.md

Add modules.nuxtjs.org to readme.md

---

README.md

Add website using Nuxt and Supabase.

feat: add clinicgeek to list of projects

---

README.md

Add website using Nuxt, Bulma and Strapi.

feat: add lifelog to list of projects

---

README.md

Added my website, [Whyp](https://github.com/whyp-website).

feat: add Whyp to Showcase

---

README.md

Cool project built in Quebec city with Nuxt

feat: add 311 Québec City project using nuxt

---

README.md

We would like to add my site to showcase list.
Thank you for your time for reviewing this PR.

feat: add ucanstock.com to showcase list

---

README.md

add the nuxt-icon-font module to the module list

add nuxt-icon-font module

---

README.md

When to use nuxt vs vanilla vue

feat: add nuxt-vs-vue-when-to-use

---

README.md

The #414 was conflicting. so I created a new PR 😄

feat: add @nuxtjs/storybook to community modules

---

README.md

Please feel free to give your comments and suggestions in the project repository, spread the love!

Added empire-admin template repository

---

README.md

Nuxt module for the Headway changelog widget

feat: add nuxt-headway module

---

README.md

Hey @pi0 
just removing the fontawesome module here.
Cheers!

feat: edit fontawesome module link

---

README.md

Docs: https://alireza-ab.ir/datepicker/installation#nuxt

feat: add "Persian Datepicker" module

---

README.md

serverMiddleware for nuxt with html2canvas proxy

feat: Add nuxt-html2canvas-proxy

---

README.md

Added "Vue - The Road To Enterprise" to the Showcase section.

feat: add The Road To Enterprise showcase

---

README.md

Nuxt module for integrating paystack payment gateway in your Nuxt application. 😁

feat: add nuxt-paystack module

---

README.md

Added nuxt-router-ui to the community modules section

feat: add nuxt-router-ui module

---

README.md

Web3.js integration module for dApps purpose 😄

feat: add nuxt-web3 community module

---

README.md

Add links to dev.to, deploying nuxt.js serverless way on to google cloud run

added deploying nuxt.js to cloud run tutorial to 2020

---

README.md

Add two super easy changes for starters that can dramatically improve the performance to 2019

feat: add easy changes for improve performance in 2019 tutorial

---

README.md

feat: add nuxt-netlify-cache module

---

README.md

Nuxtent has been deprecated, please checkout Nuxt Content: https://content.nuxtjs.org

Removed it because deprecated

---

README.md

- Nuxt branch https://github.com/kodadot/nft-gallery - slowly moving towards closer nuxt v3

feat: added KodaDot to 420 line

---

README.md

Out of the box Tailwind components for Nuxt.js 👍🏻

feat: added Tailvue Nuxt components

---

README.md

Had to remove modules due to issues with the company. Sorry for the changes

remove BigCommerce and Adyen modules

---

README.md

Hi, I just released a new module for Nuxt 3 regarding Cache.
Repo -> https://github.com/nuxt-modules/cache
Docs -> https://cache-nm.netlify.app/

feat: add @nuxt-modules/cache module for Nuxt 3

---

README.md

Klevu is an AI powered search, category merchandizing, and recommendations service for eCommerce. This is a fully working example using a public demo account.

Adding Nuxt 3 + Klevu Discovery Suite example

---

README.md

Hey peeps,
I've added Flowbite's Nuxt.js integration to the tools category as an open-source UI component library.
Cheers,
Zoltan

New: add flowbite component library as a tool
