- README.md
Looks like Medium Blog [https://medium.com/@nuxt_js](https://medium.com/@nuxt_js) has been deleted.
> Medium blog no longer exists!

- README.md
Recently we have started to make separate repositories for well-maintained modules, also an increasing number of modules are coming every day from both nuxt-community members and 3rd party persons. Just thought it is now OK to make [modules](https://github.com/nuxt-community/modules) repo just a container for smaller ones and moving the list here.
PS: please suggest more items if i've missed anything
PSS: [Preview](https://github.com/nuxt-community/awesome-nuxt/tree/modules)
PSSS: xref #6
> [WIP] Modules Section

- README.md
Add travelme.jp to Showcase.
travelme.jp is a website in Japan introducing a lot of travel articles.
> Added Showcase Project

- README.md
We've written a tutorial about how to use a headless CMS like @storyblok with Nuxt.
- Tutorial: https://www.storyblok.com/tp/headless-cms-nuxtjs (added in this PR)
- Source: https://github.com/storyblok/nuxtjs (included in the Tutorial)
> Adds "how to use a headless CMS to Nuxt" to Tutorials

- README.md
Express template hot is a copy of express template which separates nuxt and the api server in development mode, but connects the two using a proxy attached to the nuxt server. This prevents file changes from breaking hot reloading of nuxt and the api server reloads faster via live reload as well because it does not need to compile nuxt. You may read more in the backpack readme about the issue.
> Add express-template-hot to starter template list

- README.md
Vue.js Warehouse is a Cross-browser storage for Vue.js and Nuxt.js, with plugins support and easy extensibility based on Store.js.
> Add Vue.js Warehouse to the Community Modules

- README.md
Made a small mistake in the previous PR to add nuxt-vuex-router-sync to modules list, sorry about that.
> Fix nuxt-vuex-router-sync repo link

- README.md
Updated broken demo links in "Official Examples" to their respective github repos or nuxtjs.org pages where applicable. Removed deprecated "Starter" example.
> fix broken links in official examples

- README.md
Another Electron starter template with separation of the renderer process and the main process that fully written in TypeScript.
> Add electron-nuxt-ts to starter templates

- README.md
Sails.js is a complete framework to build web application and works well with nuxt.js for the client-side.
This template disable the client-side of sails.js and use nuxt instead.
> add a starter template to use nuxt with sails.js

- README.md
Although nuxt-memwatch is also a module, I think its better in place under tools then under modules.
Thanks
> add nuxt-memwatch

- README.md
I created a starter for integrating data from the Ghost blogging platform using Ghost's updated Content API for using Ghost as a headless CMS. The data can be used with the nuxt generate command to create a fully static blog for deployment on netlify.
I found this helpful as there was a lot of content on using Ghost with Gatsby, but not with nuxt.
If you think this fits better under blog or otherwise (not at all), let me know!
> Add ghost-nuxt-starter

- README.md
Electron-nuxt is the boilerplate for making electron applications built with vue / nuxt.
Documentation: https://github.com/michalzaq12/electron-nuxt#documentation
> Added electron-nuxt boilerplate.

- README.md
The official scaffolding tool for Nuxt.js projects is missing.
- https://github.com/nuxt/create-nuxt-app
> add create-nuxt-app

- README.md
Changed the name of the module and description because Kentico Cloud has been rebranded to Kentico Kontent
> Changed kenticocloud-nuxt-module to kentico-kontent-nuxt-module

- README.md
Adds new `nuxt laravel` and `nuxt laravel build` commands with sensible defaults for work with a laravel backend.
Written in typescript and tested with jest.
Provides provisionary types for @nuxt/cli
Repo: https://github.com/m2sd/nuxt-laravel
> Nuxt cli extension for work with laravel

- README.md
From project Github:
> ⚠️ We are closing the support for this package and transferred to the official community package. So we strongly suggest that you use the official community package @nuxtjs/style-resources.
> Remove deprecated nuxt-sass-resources-loader

- README.md
I've made this module because i can't `generate` my website and i was calling 4 different types of `static API` in my `nuxtServerInit action`. These calls are slowing down my website because the server need time to response to every request.
Now i can pre-generate all of these requests during the build-process and i have only 1 request (made by webpack) in the nuxtServerInit.
In this way, i'm also protecting my data because i don't have to expose the `data.json` file in the `static/` dir.
> Added nuxt-apis-to-file to Modules

- README.md
This PR adds https://github.com/hex-digital/nuxtpress to the list of Starter Kits.
It is a modern Nuxt + headless WordPress starter kit; dockerised, SEO-friendly and with development and testing tools pre-integrated. 
It has several sites deployed to Production built with it so far, including a university department page, a large UK and US based restaurant chain and a managed hosting company.
> Add NuxtPress to the list of Starter Kits

- README.md
While searching around for examples of Cypress testing Nuxt functionality, I couldn't find much content or many examples for Nuxt. The only example on awesome-nuxt was a starter kit with Cypress pre-installed, but the one example it included was very basic DOM testing.
The https://github.com/hex-digital/nuxt-cypress-example repo is a showcase of examples of Cypress testing your features within a Nuxt application. It currently shows visiting pages, DOM testing, submitting a form and testing the store, including login with Nuxt auth.
-=-
While looking for a place to add this repo, we were unsure what category to place it under. While it could be used as a Starter Kit, that's not really its intention. It's not a website to showcase, so I wasn't sure about putting it under that category …
> Add 'Community Examples' heading, with nuxt-cypress-example repo

- README.md
This PR adds https://github.com/hex-digital/nuxt-intercom to the list of Community Modules.
This module allows the simple addition of Intercom, a common live-chat application. It augments it with functionality that allows it to work inside an SPA or Universal app.
> Add nuxt-intercom to list of community modules

- README.md
Module to inject [canvas-sketch](https://github.com/mattdesl/canvas-sketch) draw methods.
These library was born for the purpose of making generative art (or threejs art) with nuxt.
> Added nuxt-canvas-sketch to Modules

- README.md
noting that the older URL no longer works
> update URL for GTM module

- README.md
Currently compression with Brotli in list is only for on the fly. 
This module helps to serve precompressed gzip and brotli assets, and compresses it and build time.
https://www.npmjs.com/package/nuxt-precompress
> Add nuxt-precompress to modules

- README.md
Added a link to the [nuxt-gmaps](https://gitlab.com/broj42/nuxt-gmaps) module, which I use since a while.
> Add nuxt-gmaps module

- README.md
Added a link to nuxt-highlightjs module, for code syntax highlighting on nuxt sites.
> Add nuxt-highlightjs module

- README.md
Add `vue-notion` to the list, which allows using Notion as a CMS for Nuxt sites.
> feat: add vue-notion

- README.md
When Nuxt.js were build, they created a module that could generate SVG as an icon-font file. Font files, css, stylus, less, sass are created and can be easily created and used inside Nuxt.js.
> feat: add nuxt-iconfont-generator module

- README.md
Since we extract markdownit module from `nuxt-community/modules`, we need to update this one too :)
> feat: update markdownit module url

- README.md
Add nuxt-humans-txt community module. Enables integration of the [HumansTxt organization project](http://humanstxt.org) for Nuxt.
> feat: add nuxt-humans-txt community module

- README.md
Update component-cache module to continue extraction of `community-modules`
> docs: change component-cache module url

- README.md
Add [nuxt-jsonapi](https://github.com/patrickcate/nuxt-jsonapi) community module. Enables easy [JSON:API](https://jsonapi.org) client integration for Nuxt.
> feat: add nuxt-jsonapi community module

- README.md
Create a documentation with @nuxt/netlify-cms-docs
* CLI based generation
* Netlify CMS content manager
NPM: https://www.npmjs.com/package/create-nuxt-netlify-cms-docs
Github: https://github.com/RoboMx/create-nuxt-netlify-cms-docs
> feat: add create-nuxt-netlify-cms-docs

- README.md
Add nuxtjs-public-google-sheets-parser community module.
Using this, easily import data from published Google Sheets.
> feat: add nuxtjs-public-google-sheets-parser

- README.md
https://github.com/danielkellyio/nuxt-content-algolia
Automatically (during npm run generate) sync content stored in your project with nuxt content to an Algolia index. This allows you to manage your content in your repo while providing powerful search capabilities to your site users.
Works great with sites hosted on Netlify, etc that automatically run your build command when you commit new content.
> feat: add nuxt-content-algolia module

- README.md
Github repo for Empire Admin has a harmful link with redirects, would be best to remove until the demo link is fixed.
> docs: Removed Empire Admin

- README.md
Currently supporting:
* Easier configuration for Adyen dropin and Checkout in a form of a Nuxt module
* AdyenCheckout.vue component ready to embed in your website
* Simple error handling
Upcoming:
* Full payment support handled on the backend
* More customizability options for AdyenCheckout component.
* Allow Card component customization
> feat: add Adyen Payment Module for Nuxt

- README.md
I was asked to change the organization name.
> rename @nuxt-commerce to @nuxt-modules

- README.md
This module adds a soft-block to websites it is added to that displays a message or redirects users from Russia or Belarus during the invasion of Ukraine.
> feat: add nuxt-block-russia-belarus module.

- README.md
Cudo Compute - Democratised cloud platform built with nuxt3, @nuxt/content and tailwind.
[https://www.cudocompute.com/](https://www.cudocompute.com/)
More info: 
Cudo Compute offers a way to buy cloud infrastructure from data centers around the world. Instead of owning the data center infrastructure, we use existing data centers to provide our service.
The goal is to create a cloud platform that works for traditional data centers (instead of the monopolies) as well as customers looking for cloud infrastructure.
> feat: add cudo compute to projects
